language: c

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgd2-noxpm-dev
  - git clone https://github.com/ansilove/libansilove.git
  - cd libansilove && cmake . && make
  - sudo make install
  - cd -
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

script: cmake . && make

env:
  global:
    # travis encrypt -r ansilove/ansilove encrypt COVERITY_SCAN_TOKEN=token
    - secure: "Ahg+dD6BwZqYTl+xTbNqBBr6Qoh7jQswegP77gxfk09UbcLSTpTQcvCLzJtumCajWXTe5HD3lD1xBghxRPNwD/+JRg25AzUeowPvBQkosDZyxMZyeQQEGPVMoD9UbnGaWhxIxYaQ7bxVCu2CJ2PcibsJ3kselnqSicEnw99TXjU="

addons:
  coverity_scan:
    project:
      name: "ansilove/ansilove"
      version: 4.0.0
      description: "ANSi / ASCII art to PNG converter in C"
    notification_email: fred@statdns.com
    build_command_prepend: cmake .
    build_command: make -j 4
    branch_pattern: master
